### ISSUE TITLE
New repository not obvious

### ISSUE THREAD

**Issue by adamlwgriffiths** [joaolcorreia/WAUnit#1]
Came here from [PyPi](https://pypi.python.org/pypi/waunit/0.0.4a1).
The repository just shows as empty with no redirect, no description, and no content.

Only when browsing to your [list of repositories](https://github.com/joaolcorreia?tab=repositories) did I see a label stating that the repository has been moved `See https://github.com/blast-analytics-marketing/WAUnit`.

Would be good if you could update the PyPi homepage value and put a README or something appropriate with a notification of the move.

**Comment by joaolcorreia** [comment]
Sorry @adamlwgriffiths this is the correct repository.
