### ISSUE TITLE
Migration to Python 3?

### ISSUE THREAD

**Issue by VinceCabs** [joaolcorreia/WAUnit#5]
Hi @joaolcorreia @joechristopher ,

Just two quick questions: 

- do you intend to migrate du Python3? We think WAUnit is great but we struggle to get it work with our platforms.
- do you provide any consulting around this solution?

**Comment by joaolcorreia** [comment]
Hi @VinceCabs, I've built a while ago ... have you checked https://datatrue.com/ and https://iterative.ly/? Seems there's no point in investing this when there are very good commercial tools around!.

**Comment by VinceCabs** [comment]
Hi @joaolcorreia,

Thanks very much for those pointers, I'll look carefully into it.
